direction: right

# --- 0. STYLES ---
style: {
  opacity: 0.0
  fill: transparent
}

# --- 1. SETTINGS ---
classes: {
  entity: {
    shape: rectangle
    style: {border-radius: 10; fill: "#FFFFFF"; stroke: "#333333"}
  }
  rel: {
    shape: diamond
    style: {fill: "#F2F2F7"; stroke: "#8E8E93"}
  }
  attr: {
    shape: oval
    # width: 100; height: 50
    style: {fill: "#F0F8FF"; stroke: "#4682B4"; stroke-dash: 3}
  }
}

# --- 2. ENTITIES ---
ADMINS: {class: entity}
DATPHONG: {class: entity}
DICHVU: {class: entity}
LOAIPHONG: {class: entity}
PAYMENTS: {class: entity}
PERMISSIONS: {class: entity}
PHONG: {class: entity}
REFUNDS: {class: entity}
REVIEWS: {class: entity}
ROLES: {class: entity}
USERS: {class: entity}
VOUCHERS: {class: entity}

# --- 3. RELATIONSHIPS ---
# (n, n): được tô sáng để dễ nhận diện

ADMINS -- REFUNDS: (1, n)
ADMINS -- ROLES: (n, n) {style: {fill: orange}}
DATPHONG -- DICHVU: (n, n) {style: {fill: orange}}
DATPHONG -- PHONG: (n, n) {style: {fill: orange}}
DATPHONG -- REVIEWS: (1, 1)
DATPHONG -- VOUCHERS: (n, 1)
PAYMENTS -- DATPHONG: (n, 1)
PAYMENTS -- REFUNDS: (1, n)
PHONG -- LOAIPHONG: (n, 1)
USERS -- DATPHONG: (1, n)
USERS -- PAYMENTS: (1, n)
USERS -- REFUNDS: (1, n)
USERS -- REVIEWS: (1, n)
ROLES -- PERMISSIONS: (n, n) {style: {fill: orange}}
